### ISSUE TITLE
Run acceptance tests against Prefect server in Docker Compose

### ISSUE THREAD

**Issue by mitchnielsen** [PrefectHQ/terraform-provider-prefect#192]
## Summary

In [https://github.com/PrefectHQ/terraform-provider-prefect/issues/186](https://github.com/PrefectHQ/terraform-provider-prefect/issues/186), we added support for running Prefect in Docker Compose and being able to test `terraform plan/apply` commands against it.

This is helpful for local development and testing, but we may also be able to use this in CI.

We could replace the [PREFECT_API_URL value in the CI file](https://github.com/PrefectHQ/terraform-provider-prefect/blob/e1bd4cf39a60be016b2f8764d75b422e423fb89e/.github/workflows/acceptance-tests.yaml#L52) to point to something like `http://localhost:4200`, and tell CI to spin up Prefect using the Docker Compose configuration.

This means we'd be testing in an ephemeral instance of Prefect instead of against dev/staging environments, which can cause transient errors due to environment pollution.

One caveat [mentioned](https://github.com/PrefectHQ/terraform-provider-prefect/pull/187#issuecomment-2145989654) by @parkedwards:

> just a caveat - one wrinkle is that our OSS server isn't an exact match/port of our SaaS (which the current acceptance tests are mostly oriented towards supporting) - the OSS server has a subset of features and endpoints. so there may be some extra potholes we hit as we try to marry the tests<>this local prefect server instance. but i like where this is going

## References

* [https://pkg.go.dev/testing#hdr-Skipping](https://pkg.go.dev/testing#hdr-Skipping)
* [https://peter.bourgon.org/blog/2021/04/02/dont-use-build-tags-for-integration-tests.html](https://peter.bourgon.org/blog/2021/04/02/dont-use-build-tags-for-integration-tests.html)
* [https://konradreiche.com/blog/how-to-separate-integration-tests-in-go/](https://konradreiche.com/blog/how-to-separate-integration-tests-in-go/)
* [https://filipnikolovski.com/posts/separating-tests-in-go/](https://filipnikolovski.com/posts/separating-tests-in-go/)

## CI draft

```
      # Run OSS tests before Cloud tests because they are faster
      # and do not use Cloud resources. This should result in a
      # faster feedback loop.
      - name: Run acceptance tests (OSS)
        run: make testacc-oss
        env:
          PREFECT_API_URL: http://localhost:4200/api
          # Temporary: only run tests we've added so far
          TESTS: TestAccResource_flow
```

## Acceptance criteria

- [X] Acceptance tests can be run against an instance of Prefect started via Docker Compose
- [X] All resources are covered for OSS or skipped if not compatible with OSS
- [X] CI uses this same setup -> [https://github.com/PrefectHQ/terraform-provider-prefect/pull/502](https://github.com/PrefectHQ/terraform-provider-prefect/pull/502)
- [X] Contribution docs explain how to test against both
- [ ] Docs state that we're compatible with OSS and Cloud
