### ISSUE TITLE
deployment id changes with terraform update

### ISSUE THREAD

**Issue by tejalal** [PrefectHQ/terraform-provider-prefect#508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version
Terraform v1.11.4
on windows_amd64
+ provider registry.terraform.io/prefecthq/prefect v2.26.0

### Affected Resource(s)
prefect deployment

### Terraform Configuration Files

```terraform
# deployment created with terraform
# ref link: https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/deployment


resource "prefect_deployment" "deployment" {
  name                     = "my-deployment"
  description              = "string"
  workspace_id             = prefect_workspace.workspace.id
  flow_id                  = prefect_flow.flow.id
  entrypoint               = "hello_world.py:hello_world"
  tags                     = ["test"]
  enforce_parameter_schema = false
  job_variables = jsonencode({
    "env" : { "some-key" : "some-value" }
  })
  parameters = jsonencode({
    "some-parameter" : "some-value",
    "some-parameter2" : "some-value2"
  })
  parameter_openapi_schema = jsonencode({
    "type" : "object",
    "properties" : {
      "some-parameter" : { "type" : "string" }
      "some-parameter2" : { "type" : "string" }
    }
  })
  path   = "./foo/bar"
  paused = false
  pull_steps = [
    {
      type               = "git_clone"
      repository         = "https://github.com/some/repo"
      branch             = "main"
      include_submodules = true
      access_token = "{{ prefect.blocks.secret.github-token }}
    }
  ]
  storage_document_id = prefect_block.test_gh_repository.id
  version             = "v1.1.1"
  work_pool_name      = "some-testing-pool"
  work_queue_name     = "default"
}
```

```
# deployment created with yaml updates the existing deployment
name: my-deployment
prefect-version: 3.2.11
build: null
push: null

pull:
- prefect.deployments.steps.git_clone:
    repository: https://github.com/repo/myrepo.git
    branch: main
    access_token: '{{ prefect.blocks.secret.git-block }}'

deployments:
- name: deployment1
  version: null
  tags: [test]
  description: deployment desciption
  entrypoint: myflows/flow.py:xxx
  parameters: {}
  work_pool:
    name: test-wp
    work_queue_name: default
    job_variables: {}
  schedules: []
  path: myflows/flow.py

```

### Expected Behavior
The prefect deployment (created with terraform) id should not get changed when updating prefect deployment fields pull_steps (i.e. branch).  When we do the same with **prefect deploy** CLI command it doesn't changes.
The first time it creates the deployment with the required pull_steps configuration.
When the branch is changes from **branch = "main"** to **branch = "my-branch"** and I ran **terrraform apply**, the terraform output says

**Apply complete! Resources: 1 added, 0 changed, 1 destroyed.**
and the deployment id is changed in the UI

### Actual Behavior
The prefect deployment id is changing for the prefect deployment created with Terraform (on update). However, it doesn't change with **prefect deploy** CLI command.

### Steps to Reproduce

1. `terraform apply`

### References
https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/deployment
